[build]
  functions = "lambda"
  publish = "build"
  command = "yarn build"
[functions]
  external_node_modules = ["fastify"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
