[functions]
  external_node_modules = ["fastify"]
  node_bundler = "esbuild"
  command = "yarn build"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
