global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
scrape_configs:
  - job_name: 'node_exporter'
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: ['dreamdraft.be:8080']
      labels:
        group: 'node_exporter'
  - job_name: 'prisma_exporter'
    scrape_interval: 5s
    metrics_path: /metrics/prisma
    scheme: http
    static_configs:
    - targets: ['dreamdraft.be:8080']
      labels:
        group: 'node_exporter'