name: Deploy Api

on: 
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    env:
      NODE_OPTIONS: --max_old_space_size=1536
    steps:      
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install yarn -g
      - name: Build Api
        run: | 
          yarn install
          yarn build
      - run: pm2 restart dist/index.js
