name: Deploy Api

on: 
  push: 
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=1536
      
    steps:      
      - name: SSH and Deploy Node app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/html/fantasy-api.simoen.tech
            rm yarn.lock package-lock.json
            git pull origin master
            yarn install
            yarn build
            pm2 restart edd-API --update-env
