name: Deploy Api

on: 
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    env:
      NODE_OPTIONS: --max_old_space_size=1536
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      EXTERNAL_API_KEY: ${{ secrets.EXTERNAL_API_KEY }}
      OAUTH_GOOGLE_CLIENT_ID: ${{ secrets.OAUTH_GOOGLE_CLIENT_ID }}
      OAUTH_GOOGLE_CLIENT_SECRET: ${{ secrets.OAUTH_GOOGLE_CLIENT_SECRET }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
    steps:      
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install yarn -g
      - name: Build Api
        run: | 
          yarn install
          yarn build
      - run: pm2 restart dist/index.js --update-env
