name: Deploy Api

on: 
  push: 
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=1536
      
    steps:      
      - name: SSH and Deploy Node app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo -i
            cd /var/www/api.dreamdraft.be
            git pull origin master
            sudo /usr/local/bin/yarn install
            sudo /usr/local/bin/yarn build
            sudo /usr/local/bin/pm2 restart api --update-env
            exit
